---
control:
  hosts:
    local-control:
      ansible_connection: local

appservers:
    hosts:
      gcloud-app-server:
        ansible_host: googlevm
      jenkins-server-vm:
        ansible_host: jenkinsvm
      
dbservers:
    hosts:
      azure-db-server:
          ansible_host: devopsvm